//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use crate::{DbArticleUuid, DbTagUuid};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "article_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_uuid: DbTagUuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub article_uuid: DbArticleUuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::articles::Entity",
        from = "Column::ArticleUuid",
        to = "super::articles::Column::Uuid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Articles,
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::TagUuid",
        to = "super::tags::Column::Uuid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tags,
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
