//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use domain::articles::{Article, builder::ArticleMissingTags};
use sea_orm::entity::prelude::*;

use crate::DbArticleUuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: DbArticleUuid,
    pub title: String,
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_tags::Entity")]
    ArticleTags,
}

impl Related<super::article_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleTags.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_tags::Relation::Articles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for ArticleMissingTags {
    fn from(Model { uuid, title, url }: Model) -> ArticleMissingTags {
        Article::builder().uuid(uuid).title(title).url(url)
    }
}

impl From<Article> for Model {
    fn from(
        Article {
            uuid, title, url, ..
        }: Article,
    ) -> Self {
        Model {
            uuid: uuid.into(),
            title,
            url,
        }
    }
}

#[cfg(test)]
mod tests {
    use domain::articles::{Article, builder::ArticleMissingTags};
    use uuid::Uuid;

    use crate::entities::articles::Model;

    #[test]
    fn articles_model_from_from_causes_no_change() {
        let art = basic_article();
        let converted = ArticleMissingTags::from(Model::from(art.clone()))
            .tags(vec![].into_boxed_slice())
            .build();
        assert_eq!(art, converted);
    }

    #[test]
    fn model_articles_from_from_causes_no_change() {
        let art = basic_model();
        let converted = Model::from(
            ArticleMissingTags::from(art.clone())
                .tags(vec![].into_boxed_slice())
                .build(),
        );
        assert_eq!(art, converted);
    }

    fn basic_model() -> Model {
        Model {
            uuid: Uuid::new_v4().into(),
            title: String::from("title"),
            url: String::from("url"),
        }
    }

    fn basic_article() -> Article {
        Article::builder()
            .title(String::from("title"))
            .url(String::from("url"))
            .tags(vec![].into_boxed_slice())
            .build()
    }
}
