//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
#[allow(unused)]
pub use super::article_tags::Entity as ArticleTags;
#[allow(unused)]
pub use super::articles::Entity as Articles;
#[allow(unused)]
pub use super::tags::Entity as Tags;
