//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_tags::Entity")]
    ArticleTags,
}

impl Related<super::article_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleTags.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_tags::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
