//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use domain::tags::Tag;
use sea_orm::entity::prelude::*;

use crate::DbTagUuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: DbTagUuid,
    pub name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_tags::Entity")]
    ArticleTags,
}

impl Related<super::article_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleTags.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_tags::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for Tag {
    fn from(
        Model {
            uuid,
            name,
            description,
        }: Model,
    ) -> Tag {
        Tag::builder()
            .uuid(uuid)
            .name(name)
            .description(description)
            .build()
    }
}

impl From<Tag> for Model {
    fn from(
        Tag {
            uuid,
            name,
            description,
        }: Tag,
    ) -> Self {
        Model {
            uuid: uuid.into(),
            name,
            description,
        }
    }
}
