name: Common Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  leptos-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SASS
      run: npm install -g sass
    - name: Add Nigthly
      run: rustup toolchain install nightly
        | rustup default nightly
    - name: Install Cargo Leptos
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/leptos-rs/cargo-leptos/releases/latest/download/cargo-leptos-installer.sh | sh
    - name: Add Wasm Target
      run: rustup target add wasm32-unknown-unknown
    - name: Leptos Build
      run: cargo leptos build --release -vv
      
  tests:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
    - name: Add Nigthly
      run: rustup toolchain install nightly
        | rustup default nightly
    - name: Run Tests
      run: cargo test --verbose
